name: 💡 Ideias Novas
description: Se você tem uma ideia aqui é o lugar
labels: [Ideia]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por enviar sua ideia. A comúnidade de Devs de Criciúma agradece.
  - type: textarea
    attributes:
      label: Descreva sua ideia
      description: 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alguma sugestão de stack?
      description: 